# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan Ageitos Bonaldi
title: Junior Software Developer 
email: ageitosbonaldijuan@outlook.es
website: www.github.com/jabsuk

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  jabsuk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: juanagbo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/oldImage.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Juan Ageitos Bonaldi, im a Software Developer student  

  I am most skilled in: <mark>Java</mark> and <mark>Python</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/jabsuk/ImageScaler
        # link_text: Project Website
        additional_links:
          # - title:  jabsuk/ImageScaler
          #   icon: fab fa-github
          #   url: github.com/jabsuk/ImageScaler
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          With this project I learnt more about JavaFx and Java Streams, it made me learn to code more efficent.
        description: | # this will include new lines to allow paragraphs
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Higher Vocational Training - Ies Sanvicente
        caption: 2022 - 2024
        sub_title: Cross-Platform Application Development
        quote: >

        description: | # this will include new lines to allow paragraphs
          During the first course, I didnt learn to code, it was something that I already knew due to be a self learner. But I learned 
          project structures, learn from other's mistakes and to code in a way that everyone can understund without lowering the code efficency.

          In the second course, I learned new Languages, new Frameworks, learned to keep in touch with a team to ensure that that no one falls behind
          so we can complete our tasks in the best possible way.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I like to learn new things, use them, practise them until I fully understand how it works.
      Its something that for me its important, just by using something doesn't mean you know how it works, when
      you truly know what does and how it manages to do it, then you can fully use it in the proper way.

      For me keep learning it's important, that why i want to pursue the degree in Artificial Intelligence at the University of Alicante.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
